### ISSUE TITLE
make sure you have CORS enabled

### ISSUE THREAD

**Issue by iav** [xicombd/ipfs-chrome-station#16]
On windows7 x64 runipfs daemon 0.4.9-rc2
Chrome addon shows me picture
```
Oh snap, it looks like your node is not running yet.

Please start it by running ipfs daemon on your terminal.

Also, please make sure you have CORS enabled, by running 
ipfs config --json API.HTTPHeaders '{"Access-Control-Allow-Origin": ["*"]}'

Report a problem
```
and seems like not work.
It works some time ago –
 don't now when it ended. I try to run command from message – it returns error
```
C:\>ipfs config --json API.HTTPHeaders '{"Access-Control-Allow-Origin": ["*"]}'
Error: Unknown Command "API.HTTPHeaders"
```

**Comment by no-tably** [comment]
Getting the exact same error myself. Any solutions found?

**Comment by mirorauhala** [comment]
You happen to be running on Windows, so go to your ipfs repository e.g. `C:\Users\YourUsername\.ipfs\` and edit the config file manually by in your favourite editor. Opening it via Notepad is a mess since it doesn't understand LF line ends.

Anyway, find the "API" point and update it to look like this.
![image](https://cloud.githubusercontent.com/assets/4082806/26501619/cb041166-4242-11e7-80d2-be582ab94a55.png)

Restart ipfs daemon and you're done.

---

Psst. Here it is for easy copying

```json 
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Origin": [
        "*"
      ]
    }
  },
```

**Comment by iav** [comment]
Thank you, @mirorauhala , you solve my case.

**Comment by mirorauhala** [comment]
@iav nice to be useful once in a while!
